### ISSUE TITLE
[bug] next event not loading after an empty event

### ISSUE THREAD

**Issue by lperovskaya** [icpc/gallery#12]
https://news.icpc.global/gallery/?album=2017&event=New+RCD+Workshop

I guess here even if I scroll down I don't see any further events, even though they exist

**Comment by azat-ismagilov** [comment]
@lperovskaya should be fixed now, please close once confirmed. 
http://icpc.io/gallery/?album=2017&event=RCD+Symposium

**Comment by lperovskaya** [comment]
works now
https://news.icpc.global/galleryNAC/?album=RC+2021-2022&event=Photo+Tour
