### ISSUE TITLE
Slideshow mode from URL

### ISSUE THREAD

**Issue by lperovskaya** [icpc/gallery#13]
Would be nice to have a way to share URL that automatically starts a fullscreen slideshow of given filter

**Comment by azat-ismagilov** [comment]
@lperovskaya should be fixed, can you confirm?

**Comment by lperovskaya** [comment]
starting from 52492246183 filter by album=2021&event=Photo+Tour
https://news.icpc.global/gallery/?album=2021&event=Photo+Tour&photo=52492246183&slideshow=true
